In [1]:
import numpy as np

In [2]:
X=np.random.randint(0,5001,size=(1000,20))
print(X)

[[4481 3582 4250 ... 2993 3931 1543]
 [2953 2425  446 ... 3966 1433 3027]
 [2344 3864 2208 ... 4850   70 4666]
 ...
 [1437 4477 3947 ... 4496 4837 3215]
 [4581  136 4998 ...  538 3428 4009]
 [ 327 1591  303 ... 3310 3434  709]]


In [3]:
# Average of the values in each column of X
ave_cols =np.mean(X, axis=0)

# Standard Deviation of the values in each column of X
std_cols = np.std(X, axis=0)

In [4]:
# Print the shape of ave_cols
print("The shape of ave_cols is: ", ave_cols.shape)

# Print the shape of std_cols
print("The shape of std_cols is: ", std_cols.shape)

The shape of ave_cols is:  (20,)
The shape of std_cols is:  (20,)


In [5]:
# Mean Normalize:

X_norm=(X -  ave_cols) / std_cols

In [6]:
# Print the average of all the values of X_norms

print("The average of all the values of X_norm is :")
print(np.mean(X_norm))
print(X_norm.mean())

# Print the average of the minimum value in each column of X_norm

print("The average of the minimum value in each column of X_norm is: ")
print(X_norm.min(axis = 0).mean())
print(np.mean(np.sort(X_norm, axis=0)[0]))

# Print the average of the maximum value in each column of X_norm

print("The average of the maximum value in each column of X_norm is: ")
print(np.mean(np.sort(X_norm, axis=0)[-1]))
print(X_norm.max(axis = 0).mean())

The average of all the values of X_norm is :
2.717825964282383e-17
2.717825964282383e-17
The average of the minimum value in each column of X_norm is: 
-1.7302635404386546
-1.7302635404386546
The average of the maximum value in each column of X_norm is: 
1.7486009631670556
1.7486009631670556


In [7]:
''' Data Seperation'''

' Data Seperation'

In [8]:
# Create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`
row_indices = np.random.permutation(X_norm.shape[0])

In [9]:
sixty=int(len(X_norm)*0.6)

eighty= int(len(X_norm)*0.8)

# Training set
X_train= X_norm[row_indices[:sixty], :]

# Create a Cross validation Set
X_crossVal=X_norm[row_indices[sixty:eighty], :]

# Create a test
X_test=X_norm[row_indices[eighty: ], :]

In [10]:
print(X_train.shape)

print(X_crossVal.shape)

print(X_test.shape)

(600, 20)
(200, 20)
(200, 20)
