In [2]:
''' Problem ": Use Broadcasting to create a 4 x 4 ndarray that has its first column full of 1s, its second column full of 2s,
its third column full of 3s, etc..'''

import numpy as np

# Replace None with appropriate code
X = np.ones((4,4))*np.arange(1,5)
print(X)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]
