In [2]:
import numpy as np
x=np.array([1,2,3,4,5])

In [3]:
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
x.dtype

dtype('int32')

In [5]:
x.shape

(5,)

In [6]:
y=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
y.shape

(3, 3)

In [8]:
y.size

9

In [9]:
x=np.array(['Hello','World'])
print(x)

['Hello' 'World']


In [10]:
print(x.shape)
print(type(x))
print(x.dtype)

(2,)
<class 'numpy.ndarray'>
<U5


In [11]:
## We create a rank 1 ndarray that contains integers
x = np.array([1,2,3])

## We create a rank 1 ndarray that contains floats
y = np.array([1.0,2.0,3.0])

## We create a rank 1 ndarray that contains integers and floats
z = np.array([1, 2.5, 4])

## We print the dtype of each ndarray
print('The elements in x are of type:', x.dtype)
print('The elements in y are of type:', y.dtype)
print('The elements in z are of type:', z.dtype)

The elements in x are of type: int32
The elements in y are of type: float64
The elements in z are of type: float64


In [12]:
## We create a rank 1 ndarray of floats but set the dtype to int64
x = np.array([1.5, 2.2, 3.7, 4.0, 5.9], dtype = np.int64)

## We print the dtype x
print('x = ', x)
print('The elements in x are of type:', x.dtype)

x =  [1 2 3 4 5]
The elements in x are of type: int64
