In [1]:
import numpy as np

In [3]:
# numpy.sort(array, axis=-1, kind=None, order=None)

'''It returns a sorted copy of an array. The axis denotes the axis along which to sort. It can take values in the range -1 to (ndim-1). Axis can take the following possible values for a given 2-D ndarray:

If nothing is specified, the default value is axis = -1, which sorts along the last axis. In the case of a given 2-D ndarray, the last axis value is 1.
If explicitly axis = None is specified, the array is flattened before sorting. It will return a 1-D array.
If axis = 0 is specified for a given 2-D array - For one column at a time, the function will sort all rows, without disturbing other elements. In the final output, you will see that each column has been sorted individually.
The output of axis = 1 for a given 2-D array is vice-versa for axis = 0. In the final output, you will see that each row has been sorted individually.'''

'It returns a sorted copy of an array. The axis denotes the axis along which to sort. It can take values in the range -1 to (ndim-1). Axis can take the following possible values for a given 2-D ndarray:\n\nIf nothing is specified, the default value is axis = -1, which sorts along the last axis. In the case of a given 2-D ndarray, the last axis value is 1.\nIf explicitly axis = None is specified, the array is flattened before sorting. It will return a 1-D array.\nIf axis = 0 is specified for a given 2-D array - For one column at a time, the function will sort all rows, without disturbing other elements. In the final output, you will see that each column has been sorted individually.\nThe output of axis = 1 for a given 2-D array is vice-versa for axis = 0. In the final output, you will see that each row has been sorted individually.'

In [4]:
# We create an unsorted rank 2 ndarray
X = np.random.randint(1,11,size=(5,5))

# We print X
print()
print('Original X = \n', X)
print()

# We sort the columns of X and print the sorted array
print()
print('X with sorted columns :\n', np.sort(X, axis = 0))

# We sort the rows of X and print the sorted array
print()
print('X with sorted rows :\n', np.sort(X, axis = 1))


Original X = 
 [[ 8  8  8  6  9]
 [ 1  4  5  1  7]
 [ 4  9  8 10  7]
 [ 5  6  4  3  1]
 [ 8  3  3  1  4]]


X with sorted columns :
 [[ 1  3  3  1  1]
 [ 4  4  4  1  4]
 [ 5  6  5  3  7]
 [ 8  8  8  6  7]
 [ 8  9  8 10  9]]

X with sorted rows :
 [[ 6  8  8  8  9]
 [ 1  1  4  5  7]
 [ 4  7  8  9 10]
 [ 1  3  4  5  6]
 [ 1  3  3  4  8]]
